string="HELLO THERE MATE"
num="1234567891234567"
string1="HELLO\tTHERE\tMATE"
string2="HELLO\nTHERE\nMATE"
name={"firstname":"Kanthimahtinathan","lastname":"Ramasubramanian"}
trans_table=str.maketrans(string,num)
word="HELLO".translate(trans_table)
#print(dir(string))
print("Capitalize    :",string.capitalize())
print("Casefold      :",string.casefold())
print("Center        :",string.center(30,"*"))
print("Ljust         :",string.ljust(30,"*"))
print("Rjust         :",string.rjust(30,"*"))
print("Count of 'E'  :",string.count("E"))
print("Encode        :",string.encode("ascii","ignore"))
print("Endswith 'ATE':",string.endswith("ATE"))
print("Expandtabs    :",string1.expandtabs(tabsize=10))
print("Find 'E'      :",string.find("E"))
print("Find 'E' index:",string.find("E",6,12))
print("RFind 'E'     :",string.rfind("E"))
print("Format        : {},{}".format("food","shelter"))
print("Formatmap Name:{firstname} {lastname}".format_map(name))
print("Index of 'T'  :",string.index("T"))
print("RIndex of 'T' :",string.rindex("T"))
print("Issalum       :",string.isalnum())
print("Isalpha       :",string[:5].isalpha())
print("Isdecimal     :",string.isdecimal())
print("Isdigit       :",string.isdigit())
print("Isidentifier  :",string.isidentifier())
print("Islower       :",string.islower())
print("Isupper       :",string.isupper())
print("Isnumeric     :",string.isnumeric())
print("Isspace       :",string1[5].isspace())
print("Istitle       :",string.istitle())
print("Join          :","*".join(string))
print("Lower         :",string.lower())
print("Upper         :",string.upper())
print("strip         :",string.strip("MATE"))
print("lstrip        :",string.lstrip("HELLO"))
print("rstrip        :",string.rstrip("MATE"))
print("trans HELLO   :",word)
print("Partiton      :",string1.partition("\t"))
print("RPartiton     :",string1.rpartition("\t"))
print("Replace       :",string.replace("HELLO","BYE"))
print("Split         :",string1.split("\t"))
print("RSplit        :",string1.rsplit("\t",1))
print("Splitlines    :",string2.splitlines())
print("Startswith HEL:",string.startswith("HEL"))
print("Swapcase      :",string.swapcase())
print("Title         :",string.title())
print("Trans  'THERE':","THERE".translate(trans_table))
print("Zfill         :",string.zfill(20))